/* eslint-disable @next/next/no-img-element */

/** Styles **/
import styles from '@/styles/Home.module.css';

/**  Next.js imports **/
import Head from 'next/head';
import Image from 'next/image';

/** Components **/
import Navbar from '@/components/navbar/navbar';
import Footer from '@/components/footer/footer';
import ProductCollection from '@/components/product-collection/productCollection';

/***  Constants ***/
const storeName: string = 'Hype Club';

export default function Home() {
  return (
    <>
      <Head>
        <title>Tuti Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Navbar storeName={storeName}></Navbar>
      <main>
        {/* For non-mobile view want to add 3 images akin to pillars  */}
        <img
          // probably need to change to next/Image
          className={styles['landing-page-img']}
          alt="landing page"
          src={'/air-jordan-orange.jpg'}
        />
        {/* I should add this over the landing page image overtop in a cool way */}
        {/* <div>The Time For Hype... Is Now</div>  */}
        <ProductCollection collectionName={'New Releases'} numberOfItems={6} />
        <ProductCollection collectionName={'Top Sellers'} numberOfItems={6} />
        <ProductCollection collectionName={'Air Jordan 1'} numberOfItems={6} />
      </main>
      <Footer />
    </>
  );
}
